services:
  - type: web
    name: my-node-ejs-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://chirag_tank_1971:Peta.nahi23@cluster0.szw6ilb.mongodb.net/phoniex?retryWrites=true&w=majority
      - key: JWT_KEY
        value: scerete

